package com.waypoint.web;

import com.waypoint.model.Applicant;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates a small, valid single-page PDF resume for a candidate with no external
 * dependencies. Byte offsets in the cross-reference table are computed from the actual
 * bytes written, so the output opens in any standard PDF viewer.
 *
 * <p>This is placeholder content standing in for a real uploaded resume document.
 */
final class ResumePdf {

    private static final int LEFT = 72;
    private static final int TOP = 720;
    private static final int WRAP = 84;

    private ResumePdf() {
    }

    static byte[] generate(Applicant applicant) {
        byte[] content = contentStream(buildLines(applicant));

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        int[] offset = new int[6];

        write(out, "%PDF-1.4\n");

        offset[1] = out.size();
        write(out, "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");

        offset[2] = out.size();
        write(out, "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");

        offset[3] = out.size();
        write(out, "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
                + "/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>\nendobj\n");

        offset[4] = out.size();
        write(out, "4 0 obj\n<< /Length " + content.length + " >>\nstream\n");
        out.writeBytes(content);
        write(out, "\nendstream\nendobj\n");

        offset[5] = out.size();
        write(out, "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica "
                + "/Encoding /WinAnsiEncoding >>\nendobj\n");

        int xref = out.size();
        write(out, "xref\n0 6\n");
        write(out, "0000000000 65535 f \n");
        for (int i = 1; i <= 5; i++) {
            write(out, String.format("%010d 00000 n \n", offset[i]));
        }
        write(out, "trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n" + xref + "\n%%EOF");

        return out.toByteArray();
    }

    private static List<String> buildLines(Applicant a) {
        List<String> lines = new ArrayList<>();
        lines.add(a.name());
        lines.add(a.posting());
        lines.add("");
        lines.add("Applied: " + a.appliedOn());
        lines.add("Resume score: " + a.resumeScore() + " / 100");
        lines.add("Pipeline stage: " + a.stage().label());
        if (a.callTime() != null) {
            lines.add("Call scheduled: " + a.callTime());
        }
        if (a.review() != null) {
            lines.add("");
            lines.add("Reviewer notes (" + a.review().rating() + "/5):");
            lines.addAll(wrap(a.review().text(), WRAP));
            lines.add("- " + a.review().author());
        }
        lines.add("");
        lines.add("(Placeholder resume generated by Waypoint.)");
        return lines;
    }

    private static byte[] contentStream(List<String> lines) {
        StringBuilder sb = new StringBuilder();
        sb.append("BT\n/F1 20 Tf\n").append(LEFT).append(' ').append(TOP).append(" Td\n");
        for (int i = 0; i < lines.size(); i++) {
            if (i == 1) {
                sb.append("/F1 12 Tf\n");
            }
            if (i > 0) {
                sb.append("0 ").append(i == 1 ? -34 : -18).append(" Td\n");
            }
            sb.append('(').append(escape(lines.get(i))).append(") Tj\n");
        }
        sb.append("ET");
        return sb.toString().getBytes(StandardCharsets.ISO_8859_1);
    }

    private static List<String> wrap(String text, int max) {
        List<String> out = new ArrayList<>();
        StringBuilder line = new StringBuilder();
        for (String word : text.split(" ")) {
            if (line.length() > 0 && line.length() + 1 + word.length() > max) {
                out.add(line.toString());
                line.setLength(0);
            }
            if (line.length() > 0) {
                line.append(' ');
            }
            line.append(word);
        }
        if (line.length() > 0) {
            out.add(line.toString());
        }
        return out;
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)");
    }

    private static void write(ByteArrayOutputStream out, String s) {
        out.writeBytes(s.getBytes(StandardCharsets.ISO_8859_1));
    }
}
